export const ContactUS = [
  {
    id: 1,
    titleIcone : "/icons/contact-us/loc.png",
    title: "UAE",
    info: "Real Estate Dubai Representative office U Bora Commercial Tower, Office 702 Business Bay Dubai, UAE",
    callIcone: "/icons/contact-us/call.svg",
    call : "+971 (0) 4 5689330",
    emailIcon : "/icons/contact-us/massege.svg",
    email : "sales@orascomdh.com",
    siteIcon : "/icons/contact-us/site.svg",
    site : "www.orascomdh.com",
  },
  {
    id: 2,
    titleIcone : "/icons/contact-us/loc.png",
    title: "SWITZERLAND",
    info: "Orascom Development Holding AG Gotthardstrasse 12 CH-6460 Altdorf",
    callIcone: "/icons/contact-us/call.svg",
    call : "+971 (0) 4 5689330",
    emailIcon : "/icons/contact-us/massege.svg",
    email : "sales@orascomdh.com",
    siteIcon : "/icons/contact-us/site.svg",
    site : "www.orascomdh.com",
  },
  {
    id: 3,
    titleIcone : "/icons/contact-us/loc.png",
    title: "EGYPT",
    info: "Orascom Development Egypt Nile City Towers, South Tower, 9th Floor – 2005 A Corniche El Nil Cairo – Egypt 11221",
    callIcone: "/icons/contact-us/call.svg",
    call : "+971 (0) 4 5689330",
    emailIcon : "/icons/contact-us/massege.svg",
    email : "sales@orascomdh.com",
    siteIcon : "/icons/contact-us/site.svg",
    site : "www.orascomdh.com",
  },
 
]